### ISSUE TITLE
No answer after Form Input

### ISSUE THREAD

**Issue by mariusbosinceanu** [gearbox-solutions/jetstream-filemaker#1]
Ubuntu 22.04.4 LTS - WSL2 on Windows 11 (10.0.22631 Build 22631)
FMS 20.3.2.205
PHP 8.2.19
Composer version 2.7.6
Jetstream": "^5.1",

After following all the written steps, running the test server, Laravel is working but the Registration app , no. 
Screen remains locked on the same input form. After few moments, Laravel server quits.

Errors, after several refresh:

1 - [2024-05-28 08:33:48] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /home/marius/filemaker_laravel/vendor/gearbox-solutions/eloquent-filemaker/src/Services/FileMakerConnection.php:489)
[stacktrace]
#0 {main}
"} 

2 - [2024-05-28 08:46:14] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /home/marius/filemaker_laravel/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:65)
[stacktrace]
#0 {main}
"} 

3 - [2024-05-28 08:55:34] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /home/marius/filemaker_laravel/vendor/gearbox-solutions/eloquent-filemaker/src/Database/Query/FMBaseBuilder.php:607)
[stacktrace]
#0 {main}
"}  

Any suggestion ?

N.B. - Running FM Data API from Postman is working.
![Screenshot 2024-05-26 174222](https://github.com/gearbox-solutions/jetstream-filemaker/assets/87566325/c832640e-8ee0-4b08-9ade-24ae863f546d)
![Screenshot 2024-05-26 174247](https://github.com/gearbox-solutions/jetstream-filemaker/assets/87566325/e71dfcc1-0f17-453f-979d-1063419827f4)

**Comment by Smef** [comment]
It looks like a timeout connecting to your FileMaker Server. You may have a firewall blocking the connection, or your server configuration options may not be correct.

**Comment by mariusbosinceanu** [comment]
Where should I look ? If I'm running the steps for installing Laravel 10, works like a charm.

**Comment by Smef** [comment]
The cache config changed between Laravel 10, which is where you may be running into an issue. In 10 it was `CACHE_DRIVER` in the env, and in 11 it's `CACHE_STORE`.

Your `.env` should have `CACHE_STORE=file` or whatever driver you'd like to use.

**Comment by mariusbosinceanu** [comment]
BINGO ! Thank U very much, David ! (y)
